#!/bin/bash

TEST=$(ps -aux | grep "java")
PID=$(pidof java)

main ()
        {

        if [[ $TEST = *minecraft* ]]
        then
                echo "Minecraft server is online, PID: $PID"
                exit 0
        else
                echo "Minecraft server is offline."
                exit 2
        fi

        }

main;
