#!/bin/bash

TEST=$(ps -aux | grep -m 1 "java")



main ()
        {

        if [[ $TEST = *minecraft* ]]
        then
                echo "Minecraft server is online."
                exit 0
        else
                echo "Minecraft server is offline."
                exit 2
        fi

        }

main;
